import { sql } from "drizzle-orm";
import { index, integer, primaryKey, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const anonymousRuns = sqliteTable("anonymous_runs", {
  id: text("id").primaryKey(),
  gameVersion: text("game_version").notNull(),
  schemaVersion: integer("schema_version").notNull().default(2),
  seedCode: text("seed_code").notNull(),
  trait: text("trait"),
  specialTrait: text("special_trait"),
  initialCash: integer("initial_cash"),
  initialHealth: integer("initial_health"),
  initialStress: integer("initial_stress"),
  initialFamily: integer("initial_family"),
  initialKnowledge: integer("initial_knowledge"),
  initialCredit: integer("initial_credit"),
  status: text("status").notNull().default("active"),
  ending: text("ending"),
  finalAge: integer("final_age"),
  finalNetWorth: integer("final_net_worth"),
  earlyRetirement: integer("early_retirement", { mode: "boolean" }),
  achievementIds: text("achievement_ids"),
  eventCount: integer("event_count").notNull().default(0),
  lastEventSequence: integer("last_event_sequence").notNull().default(-1),
  lastEventType: text("last_event_type"),
  lastGameYear: integer("last_game_year"),
  lastAge: integer("last_age"),
  lastSeason: integer("last_season"),
  lastMonth: integer("last_month"),
  startedAt: text("started_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
}, (table) => [
  index("idx_anonymous_runs_started_at").on(table.startedAt),
  index("idx_anonymous_runs_status_version").on(table.status, table.gameVersion),
  index("idx_anonymous_runs_seed_code").on(table.seedCode),
]);

export const anonymousEvents = sqliteTable("anonymous_events", {
  id: text("id").primaryKey(),
  runId: text("run_id").notNull(),
  eventType: text("event_type").notNull(),
  gameVersion: text("game_version").notNull(),
  schemaVersion: integer("schema_version").notNull().default(2),
  eventSequence: integer("event_sequence").notNull().default(0),
  clientElapsedMs: integer("client_elapsed_ms"),
  gameYear: integer("game_year"),
  age: integer("age"),
  season: integer("season"),
  month: integer("month"),
  dataJson: text("data_json").notNull().default("{}"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("idx_anonymous_events_run_id").on(table.runId),
  index("idx_anonymous_events_type_created_at").on(table.eventType, table.createdAt),
  uniqueIndex("idx_anonymous_events_run_sequence").on(table.runId, table.eventSequence),
]);

export const analyticsDailyMetrics = sqliteTable("analytics_daily_metrics", {
  metricDate: text("metric_date").notNull(),
  gameVersion: text("game_version").notNull(),
  metricName: text("metric_name").notNull(),
  dimension: text("dimension").notNull().default("all"),
  sampleCount: integer("sample_count").notNull().default(0),
  valueTotal: integer("value_total").notNull().default(0),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  primaryKey({ columns: [table.metricDate, table.gameVersion, table.metricName, table.dimension] }),
  index("idx_analytics_daily_metrics_name_date").on(table.metricName, table.metricDate),
]);

export const analyticsSchemaStatements = [
  `CREATE TABLE IF NOT EXISTS anonymous_runs (
    id TEXT PRIMARY KEY NOT NULL,
    game_version TEXT NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 2,
    seed_code TEXT NOT NULL,
    trait TEXT,
    special_trait TEXT,
    initial_cash INTEGER,
    initial_health INTEGER,
    initial_stress INTEGER,
    initial_family INTEGER,
    initial_knowledge INTEGER,
    initial_credit INTEGER,
    status TEXT NOT NULL DEFAULT 'active',
    ending TEXT,
    final_age INTEGER,
    final_net_worth INTEGER,
    early_retirement INTEGER,
    achievement_ids TEXT,
    event_count INTEGER NOT NULL DEFAULT 0,
    last_event_sequence INTEGER NOT NULL DEFAULT -1,
    last_event_type TEXT,
    last_game_year INTEGER,
    last_age INTEGER,
    last_season INTEGER,
    last_month INTEGER,
    started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS anonymous_events (
    id TEXT PRIMARY KEY NOT NULL,
    run_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    game_version TEXT NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 2,
    event_sequence INTEGER NOT NULL DEFAULT 0,
    client_elapsed_ms INTEGER,
    game_year INTEGER,
    age INTEGER,
    season INTEGER,
    month INTEGER,
    data_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS analytics_daily_metrics (
    metric_date TEXT NOT NULL,
    game_version TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    dimension TEXT NOT NULL DEFAULT 'all',
    sample_count INTEGER NOT NULL DEFAULT 0,
    value_total INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (metric_date, game_version, metric_name, dimension)
  )`,
  "CREATE INDEX IF NOT EXISTS idx_anonymous_runs_started_at ON anonymous_runs (started_at)",
  "CREATE INDEX IF NOT EXISTS idx_anonymous_runs_status_version ON anonymous_runs (status, game_version)",
  "CREATE INDEX IF NOT EXISTS idx_anonymous_runs_seed_code ON anonymous_runs (seed_code)",
  "CREATE INDEX IF NOT EXISTS idx_anonymous_events_run_id ON anonymous_events (run_id)",
  "CREATE INDEX IF NOT EXISTS idx_anonymous_events_type_created_at ON anonymous_events (event_type, created_at)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_anonymous_events_run_sequence ON anonymous_events (run_id, event_sequence)",
  "CREATE INDEX IF NOT EXISTS idx_analytics_daily_metrics_name_date ON analytics_daily_metrics (metric_name, metric_date)",
] as const;
